/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as MentionsLegalesRouteImport } from './routes/mentions-legales'
import { Route as DirectoryRouteImport } from './routes/directory'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ConfidentialiteRouteImport } from './routes/confidentialite'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PrintCodeRouteImport } from './routes/print.$code'
import { Route as CSlugRouteImport } from './routes/c.$slug'
import { Route as AuthenticatedTemplatesRouteImport } from './routes/_authenticated.templates'
import { Route as AuthenticatedTeamRouteImport } from './routes/_authenticated.team'
import { Route as AuthenticatedProspectsRouteImport } from './routes/_authenticated.prospects'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated.profile'
import { Route as AuthenticatedPremiumRouteImport } from './routes/_authenticated.premium'
import { Route as AuthenticatedGalleryRouteImport } from './routes/_authenticated.gallery'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedBillingRouteImport } from './routes/_authenticated.billing'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const MentionsLegalesRoute = MentionsLegalesRouteImport.update({
  id: '/mentions-legales',
  path: '/mentions-legales',
  getParentRoute: () => rootRouteImport,
} as any)
const DirectoryRoute = DirectoryRouteImport.update({
  id: '/directory',
  path: '/directory',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfidentialiteRoute = ConfidentialiteRouteImport.update({
  id: '/confidentialite',
  path: '/confidentialite',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrintCodeRoute = PrintCodeRouteImport.update({
  id: '/print/$code',
  path: '/print/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const CSlugRoute = CSlugRouteImport.update({
  id: '/c/$slug',
  path: '/c/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTemplatesRoute = AuthenticatedTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTeamRoute = AuthenticatedTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProspectsRoute = AuthenticatedProspectsRouteImport.update({
  id: '/prospects',
  path: '/prospects',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPremiumRoute = AuthenticatedPremiumRouteImport.update({
  id: '/premium',
  path: '/premium',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedGalleryRoute = AuthenticatedGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBillingRoute = AuthenticatedBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/contact': typeof ContactRoute
  '/directory': typeof DirectoryRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/onboarding': typeof OnboardingRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/gallery': typeof AuthenticatedGalleryRoute
  '/premium': typeof AuthenticatedPremiumRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/prospects': typeof AuthenticatedProspectsRoute
  '/team': typeof AuthenticatedTeamRoute
  '/templates': typeof AuthenticatedTemplatesRoute
  '/c/$slug': typeof CSlugRoute
  '/print/$code': typeof PrintCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/contact': typeof ContactRoute
  '/directory': typeof DirectoryRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/onboarding': typeof OnboardingRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/gallery': typeof AuthenticatedGalleryRoute
  '/premium': typeof AuthenticatedPremiumRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/prospects': typeof AuthenticatedProspectsRoute
  '/team': typeof AuthenticatedTeamRoute
  '/templates': typeof AuthenticatedTemplatesRoute
  '/c/$slug': typeof CSlugRoute
  '/print/$code': typeof PrintCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/contact': typeof ContactRoute
  '/directory': typeof DirectoryRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/onboarding': typeof OnboardingRoute
  '/_authenticated/billing': typeof AuthenticatedBillingRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/gallery': typeof AuthenticatedGalleryRoute
  '/_authenticated/premium': typeof AuthenticatedPremiumRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/prospects': typeof AuthenticatedProspectsRoute
  '/_authenticated/team': typeof AuthenticatedTeamRoute
  '/_authenticated/templates': typeof AuthenticatedTemplatesRoute
  '/c/$slug': typeof CSlugRoute
  '/print/$code': typeof PrintCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/confidentialite'
    | '/contact'
    | '/directory'
    | '/mentions-legales'
    | '/onboarding'
    | '/billing'
    | '/dashboard'
    | '/gallery'
    | '/premium'
    | '/profile'
    | '/prospects'
    | '/team'
    | '/templates'
    | '/c/$slug'
    | '/print/$code'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/confidentialite'
    | '/contact'
    | '/directory'
    | '/mentions-legales'
    | '/onboarding'
    | '/billing'
    | '/dashboard'
    | '/gallery'
    | '/premium'
    | '/profile'
    | '/prospects'
    | '/team'
    | '/templates'
    | '/c/$slug'
    | '/print/$code'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/confidentialite'
    | '/contact'
    | '/directory'
    | '/mentions-legales'
    | '/onboarding'
    | '/_authenticated/billing'
    | '/_authenticated/dashboard'
    | '/_authenticated/gallery'
    | '/_authenticated/premium'
    | '/_authenticated/profile'
    | '/_authenticated/prospects'
    | '/_authenticated/team'
    | '/_authenticated/templates'
    | '/c/$slug'
    | '/print/$code'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  ConfidentialiteRoute: typeof ConfidentialiteRoute
  ContactRoute: typeof ContactRoute
  DirectoryRoute: typeof DirectoryRoute
  MentionsLegalesRoute: typeof MentionsLegalesRoute
  OnboardingRoute: typeof OnboardingRoute
  CSlugRoute: typeof CSlugRoute
  PrintCodeRoute: typeof PrintCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentions-legales': {
      id: '/mentions-legales'
      path: '/mentions-legales'
      fullPath: '/mentions-legales'
      preLoaderRoute: typeof MentionsLegalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/directory': {
      id: '/directory'
      path: '/directory'
      fullPath: '/directory'
      preLoaderRoute: typeof DirectoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confidentialite': {
      id: '/confidentialite'
      path: '/confidentialite'
      fullPath: '/confidentialite'
      preLoaderRoute: typeof ConfidentialiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/print/$code': {
      id: '/print/$code'
      path: '/print/$code'
      fullPath: '/print/$code'
      preLoaderRoute: typeof PrintCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$slug': {
      id: '/c/$slug'
      path: '/c/$slug'
      fullPath: '/c/$slug'
      preLoaderRoute: typeof CSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/templates': {
      id: '/_authenticated/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof AuthenticatedTemplatesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/team': {
      id: '/_authenticated/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof AuthenticatedTeamRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/prospects': {
      id: '/_authenticated/prospects'
      path: '/prospects'
      fullPath: '/prospects'
      preLoaderRoute: typeof AuthenticatedProspectsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/premium': {
      id: '/_authenticated/premium'
      path: '/premium'
      fullPath: '/premium'
      preLoaderRoute: typeof AuthenticatedPremiumRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/gallery': {
      id: '/_authenticated/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof AuthenticatedGalleryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/billing': {
      id: '/_authenticated/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AuthenticatedBillingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedBillingRoute: typeof AuthenticatedBillingRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedGalleryRoute: typeof AuthenticatedGalleryRoute
  AuthenticatedPremiumRoute: typeof AuthenticatedPremiumRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedProspectsRoute: typeof AuthenticatedProspectsRoute
  AuthenticatedTeamRoute: typeof AuthenticatedTeamRoute
  AuthenticatedTemplatesRoute: typeof AuthenticatedTemplatesRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedBillingRoute: AuthenticatedBillingRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedGalleryRoute: AuthenticatedGalleryRoute,
  AuthenticatedPremiumRoute: AuthenticatedPremiumRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedProspectsRoute: AuthenticatedProspectsRoute,
  AuthenticatedTeamRoute: AuthenticatedTeamRoute,
  AuthenticatedTemplatesRoute: AuthenticatedTemplatesRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  ConfidentialiteRoute: ConfidentialiteRoute,
  ContactRoute: ContactRoute,
  DirectoryRoute: DirectoryRoute,
  MentionsLegalesRoute: MentionsLegalesRoute,
  OnboardingRoute: OnboardingRoute,
  CSlugRoute: CSlugRoute,
  PrintCodeRoute: PrintCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
