// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oboljtsnpmxwvirfzdft.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9ib2xqdHNucG14d3ZpcmZ6ZGZ0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODE1MzUyODEsImV4cCI6MjA5NzExMTI4MX0.xfICG6ezLBTwCTUoqdG2EJD_fuT0XGN6nzLUls3jzgo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? window.localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});